### ISSUE TITLE
Include some basic mapping functionality?

### ISSUE THREAD

**Issue by richardsc** [rich-iannone/stationaRy#2]
I made an Rpubs that shows how to do some basic mapping using facilities from the `oce` package (for which I am a co-author), found here:

https://rpubs.com/clarkrichards/86727

@rich-iannone expressed an interest in including some mapping functionality in `stationaRy`, so this discussion is to narrow down what that would entail and how it would look. Some questions are:
1. What functionality could be added that would differ from directly connecting with and using other packages that provide mapping (e.g. `oce`, `sp`, etc)?
2. What kinds of maps would be general enough to include? Some examples could include:
- Station locations (as in the Rpub)
- Met values (e.g. temperature or whatever) for a certain date at a variety of stations
- Gridded (i.e. spatially interpolated) met fields
- ... ?

**Comment by rich-iannone** [comment]
I think the global view of stations using `oce` would be nice and options can be exposed for different coloring of stations by groups (e.g. by countries, by position/height, by years of consecutive data, by types of met data, by network, etc.).

Another nice implementation of mapping would be to show a map of the filtered stations when filtering the list of stations. Since that's likely to be zoomed in a bit, and perhaps have less stations overall, maybe a leaflet map might be good (with metadata bound to each of the stations).

I like the idea of gridded met fields. I suppose for that we could extract from already available global data (e.g. GDAS, reanalysis files, etc.) or develop those with something simple like CALMET.

**Comment by pssguy** [comment]
I think the leaflet idea is good and pretty easy to implement with drilldown options
I'd be interested in an indicator by stations that are closes to say a country or state capital city . Is there  such a dataset anywhere out there already?
