### ISSUE TITLE
Hi, thanks for the code! Is there a way to download the hourly precipitation? Thanks!

### ISSUE THREAD

**Issue by MartaDiaz** [rich-iannone/stationaRy#25]

**Comment by rich-iannone** [comment]
Precipitation is not one of the standard fields because a lot of met stations don’t measure precipitation. So you have to discover whether the field is present and what its coverage is.

Further complicating this, there are many measures for precipitation. Take a look at the README for how to discover additional fields and the linked document for what the fields represent. I do agree that there should be functions to make this process easier. I’ll file a separate issue for that work.
